#!/bin/bash
# This script is to be used with Docker Compose to automatically change WordPress permissions after the services have started

cd /Desktop/
sudo chown -R www-data:www-data WordPress/
sudo chmod 775 WordPress/
